[build]
  command = "npm run build"
  publish = "dist"

# Send the short code as a query parameter
[[redirects]]
  from = "/*"
  to = "https://uogilqdfcskkakmxpdcu.supabase.co/functions/v1/redirect?code=:splat"
  status = 200
  force = true